name: miscelaneos
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_riverpod: ^2.3.6
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  permission_handler: ^11.2.0
  sensors_plus: ^4.0.2
  share_plus: ^7.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
