name: miscelaneos
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.7.0
  flutter_riverpod: ^2.3.6
  go_router: ^7.0.0
  google_fonts: ^4.0.4
  permission_handler: ^10.2.0
  sensors_plus: ^2.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
